<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.0.0</Version>
    <Company>Md. Shohan Khan</Company>
    <Product>Dentiva</Product>
    <Copyright>Copyright © 2026 Md. Shohan Khan</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
